.TH querybts 1
.SH NAME
querybts \- view outstanding bug reports on a debbugs server
.SH SYNOPSIS
.B querybts
.I "[options] <package | number [number2]...>"
.SH "DESCRIPTION"
.B querybts
is designed to provide a convenient and easy-to-use interface to the
Debbugs bug tracking system, as used by Debian and several other
projects.  You can specify a package name or one or more report
numbers.
.SH OPTIONS
The program follows the usual GNU command line syntax, with long
options starting with two dashes (`\-\-').
A summary of options are included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show the version of
.B querybts
and exit.
.TP
.B \-A, \-\-archive
Browse archived bugs instead of current reports.  Debbugs servers
clear out closed reports after 28 days and place them in a separate
archive; this option allows those older, resolved reports to be viewed
(at least for servers that maintain an archive).
.TP
.B \-B SYSTEM, \-\-bts=SYSTEM
Instead of the Debian bug server, use the server specified by
.B SYSTEM.
You can specify
.B help
to get a list of supported servers.
.TP
.B \-m, \-\-mbox
Retrieve the given bug number(s) or package name(s) as a mailbox file, instead of viewing
it. It will be dumped to standard output.
.TP
.B \-\-proxy=PROXY, \-\-http_proxy=PROXY
Specify the WWW proxy server to use to handle the query of the bug
tracking system.  You should only need this parameter if you are
behind a firewall.
.TP
.B \-s, \-\-source
Query on source packages, rather than binary packages.
.TP
.B \-u, \-\-ui
Specify the user interface to use.
Valid options are \fBtext\fP, \fBurwid\fP, \fBgtk2\fP;
default is taken from the reportbug configuration files.
.TP
.B \-w, \-\-web
Launch a web browser to view bug reports, instead of using the
internal interface.  This will also allow you to see all of the
discussion about a particular bug, instead of the initial report.
(Only the first bug number on the command line will be opened.)
.SH CONFIGURATION FILES
.B querybts
supports a simple run control file syntax.  Commands are read from
.B /etc/reportbug.conf
and
.B $HOME/.reportbugrc
with commands in the latter overriding those in the former.  Commands
are not case sensitive, and currently take 0 or 1 arguments; arguments
containing whitespace must be enclosed in quotes.  Any line starting
with # is taken to be a comment and will be ignored.

Generally, options corresponding to the GNU long options for
.B querybts
are supported, without leading \-\- sequences.  See the default
.B /etc/reportbug.conf
for all acceptable options.  Options only supported by
.B reportbug
will be silently ignored.
.SH ENVIRONMENT
.TP
.B BROWSER
Colon-separated list of web browsers to try; they will be tried in
order, until one succeeds.  You can use %s to substitute the URL to be
used, and %% to insert a literal percent sign.  If no %s is specified,
the URL will be supplied as a normal argument.
.TP
.B http_proxy
Provides the address of a proxy server to handle the BTS query.  This
should be a valid
.B http
URL for a proxy server, including any required port number (simply
specifying a hostname, or omitting a port other than 80, WILL NOT WORK).
.SH NOTES
Python's getopt module is pickier than GNU getopt() about the order of
command line arguments; all switches must be specified before the
package name.
.SH "SEE ALSO"
reportbug(1), reportbug.conf(5)
.SH AUTHOR
Chris Lawrence <lawrencc@debian.org>.
