#! /bin/sh -e
#
# postinst script for Debian python packages.
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
#

#DEBHELPER#

PACKAGE=reportbug
DIRLIST="/usr/share/reportbug"

PYTHON=python2.3

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        for i in $DIRLIST ; do
            /usr/bin/$PYTHON -O /usr/lib/$PYTHON/compileall.py -q $i
            /usr/bin/$PYTHON /usr/lib/$PYTHON/compileall.py -q $i
        done
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
