#! /bin/sh -e
#
# sample prerm script for Debian python packages.
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
#

#DEBHELPER#

PACKAGE=reportbug

dpkg --listfiles $PACKAGE |
	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
	xargs rm -f >&2

