.TH reportbug 1
.SH 名前
reportbug \- debbugs サーバにバグを報告
.SH 書式
.B reportbug
.I "[オプション] <パッケージ名 | 絶対パス>"
.SH 説明
.B reportbug
は、主として Debian ディストリビューションのバグを報告するために設計
された。デフォルトでは、Debian バグ追跡システム
.I submit@bugs.debian.org
宛に、見つけたバグに関する情報を含んだ電子メールを作成し、報告者自身
宛のカーボンコピーも作成する。
.PP
.B \-\-bts
オプションを使えば、Debian バグ追跡システムである \fBdebbugs\fP を使う
他のサーバにバグを報告することもできる。
.PP
パッケージ名か絶対ファイル名のどちらかを指定できる。ファイル名を使う場
合は、それを認識させるために \fB/\fP から始めなければならない。
\fBreportbug\fP にシステム内のファイル名を検索させたい場合は、
後述の \fB\-\-file\fP オプションを参照のこと。
.SH オプション
本プログラムは通常の GNU コマンドライン構文に準じており、長いオプション
は 2 個のダッシュ (`\-\-') で始まる。
.TP
.B \-h, \-\-help
オプションの概要を表示する。
.TP
.B \-v, \-\-version
.B reportbug
のバージョンを表示して終了する。
.TP
.B \-a, \-\-af
バグ報告の校訂用としてエディタを起動する代わりに、編集および送信用として
.B af
メールリーダを使う。
.TP
.B \-A ファイル名, \-\-attach=ファイル名
バグ報告にファイルを添付する。テキストおよびバイナリファイルの両方が使用
できる。本ルーチンは、含めたファイル付の MIME 添付を作成する。いくつかの
ケース (通常はテキストファイルの場合) では、\-\-include を使う方が良いか
もしれない (Debian のバグ追跡システムは、MIME 添付対応に制限があることに
注意)。
.TP
.B \-b, \-\-no\-query\-bts
問題がすでに報告済かどうか、Debian バグ追跡システムを調べない。オフラ
インユーザや、
.B 絶対に
バグであると確信している場合に便利である。
.TP
.B \-\-query\-bts
問題がすでに報告済かどうか、Debian バグ追跡システムを調べる (デフォルト)。
.TP
.B \-B システム, \-\-bts=システム
Debian バグサーバ (あるいは \fB/etc/reportbug.conf\fP 内で指定している
バグサーバ) の代わりに、
.B システム
で指定したサーバを使う。
対応しているサーバの一覧を得るために、
.B help
を指定することもできる。
.TP
.B \-\-body=本文
メッセージ本文として指定した本文を使う。本文テキストは半角 70 文字で
整形され、通常の reportbug 用ヘッダとフッタが適切に追加される。エディ
タの確認や、あらゆる "特別な" 確認は行なわれなくなる。
.TP
.B \-\-body-file=本文ファイル名
メッセージ本文として指定した本文ファイル名のテキストファイル (とみなさ
れる) の内容を使う。このファイルは、適切に整形されている (1 行の長さが
正しいなど) ものとみなされる。通常のヘッダとフッタが追加され、エディタ
ステップと "特別な" 確認ステップは飛ばされる (本文ファイル名は、名前付
パイプを使うこともできる。デバイスの特別ファイルを使うと、予期しない結
果になるかもしれない)。
.TP
.B \-c, \-\-no\-config\-files
設定ファイルをバグ報告から確認無しに除去する。デフォルトでは、それらを
含めるかどうかの確認が行なわれる。場合によっては、設定ファイルを含める
と電子メールで重要な情報が送信されてしまうといった事態になりかねない。
.TP
.B \-\-configure
.B reportbug
の初回実行時の設定ルーチンを再実行し、新規の .reportbugrc ファイルを書き
出す。ファイル内の既存の設定は消去されるが、バックアップとして .reportbugrc~
が書き出される。
.TP
.B \-\-check\-available
packages.debian.org に対して、パッケージの新規リリース有無を調べる (デ
フォルト)。
.TP
.B \-\-no\-check\-available
packages.debian.org に対して、パッケージの新規リリース有無を調べない。
.TP
.B \-d, \-\-debug
Debian に実際のバグ報告を送信しない。代わりに、報告者自身に送信する。
これは主として、メンテナによるテスト用に使われる。
.TP
.B \-e エディタ, \-\-editor=エディタ
使うエディタを指定し、環境変数 EDITOR や VISUAL の設定を上書きする。
.TP
.B \-\-email=アドレス
送信者として報告内に現われる (つまり \fBFrom:\fP ヘッダに表示される) 電
子メールアドレスを設定する。実際のインターネット電子メールアドレス自体で
なければならない (つまり実名やコメント部分を付けてはならない)。本設定は
環境変数 EMAIL や DEBEMAIL を上書きするが、REPORTBUGEMAIL は上書きしない。
.TP
.B \-\-exit\-prompt
終了時に確認を表示する。一時的な端末で (つまり Debian メニューエントリか
ら) reportbug を実行している場合に役立つ。
.TP
.B \-f ファイル名, \-\-filename=ファイル名
.I ファイル名
が含まれているパッケージのバグを報告するので、そのファイルがどのパッケー
ジ内にあるのかを探す必要がない。ファイル名の正確なパス名がまず検索され、
その後で全ファイルを検索しようとする。
.TP
.B \-\-path
\-f オプションも指定されているなら、指定したファイル名のパスのみを検索
する。\-f オプションに絶対パス (つまり / で始まる形式) を指定すれば、
この動作は上書きされる。
.TP
.B \-g, \-\-gnupg, \-\-gpg
.B GnuPG
(GNU Privacy Gurard) を使って、バグ報告にデジタル署名を行なう (報告の
編集と送信に MUA を使っていれば、この引数は無視される)。
.TP
.B \-G, \-\-gnus
報告の送信にエディタではなく、GNUS メール・ニューズリーダを使う。
.TP
.B \-H ヘッダ, \-\-header=ヘッダ
電子メールに特別な RFC 2822 ヘッダを追加する。たとえば、
.I debian-68k@lists.linux-m68k.org
に報告のカーボンコピーを送信したければ、以下のように使用できる：
.I \-H 'X\-Debbugs\-CC: debian\-68k@lists.linux\-m68k.org'
.TP
.B \-i ファイル, \-\-include=ファイル
編集しているメッセージ本文の一部として、指定したファイルを挿入する。
複数ファイルを追加するのに、複数回使用できる。挿入するのはテキストだけ
にすること!  これは
.B bug
のバグ一覧内にある Michael Alan Dorman の提案による (\-\-attach オプ
ションも参照)。
.TP
.B \-I, \-\-no\-check\-installed
報告の送信前に、パッケージがインストール済かどうかを調べない。これは
一般に、自分のシステムには未インストールだと判っているパッケージの報
告を送信する場合のみ役立つ。
.TP
.B \-\-check\-installed
報告の送信時に、指定したパッケージがインストール済かどうかを調べる (これ
は reportbug のデフォルトの動作である)。
.TP
.B \-j 妥当性, \-\-justification=妥当性
Debian では、バグの重要度が "深刻 (serious)" や "重大 (grave)", "致命的
(critical)" などになるためには、そのように分類されるための一定の基準を
満たさなければならない。本オプションは、リリースクリティカルバグであ
ることの確認を受ける代わりに、その妥当性を指定できる。
.TP
.B \-k, \-\-kudos
記録されているメンテナのアドレス宛に、バグ報告を送信する代わりに感謝の
電子メールを送信する (Debian アーカイブ内のパッケージに対して、
\fIpackagename\fP@packages.debian.org 宛に謝意のメールを送信することも
できる。しかしながら本オプションは control ファイル内のメンテナアドレ
スを使うため、他のパッケージソースでも動作するだろう)。
.TP
.B \-K 鍵ID, \-\-keyid=鍵ID
PGP/GnuPG 署名にプライベート鍵を使う。何も指定しなければ、報告者の
電子メールアドレスにマッチする秘密キーリングの、最初の鍵が使用される。
.TP
.B \-\-license
標準出力に \fBreportbug\fP の著作権およびラインセンス情報を表示する。
.TP
.B \-\-list\-cc=アドレス
バグ報告番号が取得された後で、指定したリスト宛に報告のカーボンコピーを
送信する。
.I \-H 'X\-Debbugs\-CC: アドレス'
オプションと同じ。
.TP
.B \-m, \-\-maintonly
パッケージメンテナだけにバグ報告を送信する。バグ追跡システムは、バグ報告
配布リストにコピーを送信しない。
.TP
.B \-\-mode=モード
\fBreportbug\fP の動作モードを設定する。
.B reportbug
は、現在のところ 4 種類の動作モード \- \fBnovice\fP (デフォルト),
\fBstandard\fP, \fBadvanced\fP, \fBexpert\fP \- を備えている。

.B novice
(初級) モードは、"通常のユーザ" が知りたがらなかったり気を使いたくない
確認を最小限に抑え、メンテナにかかる些末な負荷を無くすように設計されて
いる。本モードでの新規バージョンのチェックは、安定版ディストリビュー
ションだけに行なわれる。現在のところ、デフォルトのモードである。

.B standard
(標準) モードは、確認に関しては reportbug 1.50 以前と多かれ少なかれ同じ
である。どちらかといえば多くの確認が行なわれ、無意味な報告や重複した報
告を送信しないよう、ユーザを促そうとする。

.B advanced
(上級) モードは \fBstandard\fP に似ているが、Debian の上級ユーザに適し
た近道が含まれており、\fBexpert\fP モードほど無骨  (言い争いに発展しか
ねない) ではない (現在のところ \fBstandard\fP モードとの相違点は、
"incoming" キューを熟知しているものとみなすこと、"依存" パッケージの
バグを報告できること、エディタ内ではどこに報告テキストを挿入するかを
確認しないことなどである)。

.B expert
(最上級) モードは、無意味あるいは不要なバグ報告や、"重要度のインフレ"
などを阻止するための確認を最小限にするように設計されている。expert
モードでは、
.B reportbug
はユーザが Debian ポリシを熟知しているものとみなす。実際このことは、も
はや reportbug がバグ報告の高重要度設定の妥当性を要求せず、メッセージの
いくつかの自動クリーンアップは飛ばされることを意味する。Debian プロジェ
クトに定期的に貢献していない人は、expert モードを使わないことを \fI強く\fP
推奨する。なぜなら、不適切に使うとメンテナとの言い争いになりえるからで
ある。
.TP
.B \-M, \-\-mutt
バグ報告の校訂用にエディタを起動する代わりに、編集および送信用に
.B mutt
メールリーダを使う。
.TP
.B \-\-mta='<MTA>'
.B /usr/sbin/sendmail
(デフォルト) の代わりとなる代替 MTA を指定する。これによって、あらゆる
.Bsmtphost
設定は上書きされる。
.TP
.B \-\-mua='<MUA> <オプション>'
バグ報告の校訂用にエディタを起動する代わりに、編集および送信用に指定し
た MUA (メールユーザエージェント) を使う。バグ報告をメッセージ草稿とし
て解釈するメールリーダを指定するための
.B オプション
を使わなければならない。この動作例としては、
.B --mutt, --nmh
および
.B --af
オプションの処理プロセスを参照のこと。
.TP
.B \-n, \-\-nmh, \-\-mh
バグ報告の校訂用にエディタを起動する代わりに、編集および送信用に (
.B mnh
および
.B mh
メールシステムの一部である)
.B comp
コマンドを使う。
.TP
.B \-o ファイル名, \-\-output=ファイル名
電子メールを送信する代わりに、指定したファイル名にリダイレクトする。
.TP
.B \-O, \-\-offline
あらゆる外部問い合せを無効にする。現在のところ、
\fB\-\-no\-check\-available \-\-no\-query\-bts\fP
が同じ効果を備えている。
.TP
.B \-p, \-\-print
電子メールを送信する代わりにバグ報告を標準出力へ出力するので、ファイル
へリダイレクトしたり、他のプログラムへパイプすることができる。

本オプションは、バグ報告のテンプレートを出力するだけである。詳細説明を
自分で記述する必要があるだろう。
.TP
.B \-\-paranoid
送信前に、全ヘッダも含めてメッセージの内容を表示する。テンプレートモード
では、自動的に無効となる。
.TP
.B \-\-no\-paranoid
送信前に、メッセージの全内容を表示しない (デフォルト)。
.TP
.B \-\-pgp
.PGP
(Pretty Good Privacy) を使って、バグ報告にデジタル署名を行なう。しかし
ながら、Debian プロジェクトは GnuPG を選び、PGP の使用は徐々に止めつつ
あることに注意されたい (バグ報告の編集と送信に MUA を使うのなら、本引数
は無視される)。
.TP
.B \-\-proxy=プロキシ, \-\-http_proxy=プロキシ
バグ追跡システムの問い合せを処理するのに使う WWW プロキシサーバを指定
する。ファイアウォールの背後にいる場合のみ、本パラメータが必要となるだ
ろう。プロキシ引数は、(必要なら) ポート番号も含めた正しい HTTP URL で
なければならない。例: 
\fBhttp://192.168.1.1:3128/\fP
.TP
.B \-q, \-\-quiet
標準エラーへの診断メッセージを抑制する。
.TP
.B \-Q, \-\-query\-only
バグ報告を送信せず、BTS への問い合せのみを行なう。\-\-no\-bts\-query を
指定しているのなら、本オプションは無視される。
.TP
.B \-\-query\-source
指定したバイナリパッケージだけでなく、同じソースから構築された全バイナリ
パッケージに問い合せを行なう (reportbug 2.0 以降のデフォルト動作)。
.TP
.B \-\-no\-query\-source
コマンドラインで指定されたバイナリパッケージにのみ問い合せを行なう。
.TP
.B \-\-realname=名前
バグ報告に使う実名 (人に読める名前) を設定する。
.TP
.B \-\-report\-quiet
バグ追跡システムにバグを登録するが、パッケージメンテナや、あるいはあら
ゆる人にバグ報告を送信しない。報告者が問題となっているパッケージのメン
テナである場合や、自分がしていることを本当に理解しているのでない限り、
本オプションを使うべきではない。
.TP
.B \-\-reply-to=アドレス, \-\-replyto=アドレス
バグ報告内に
.B Reply-To
アドレスヘッダを設定する。
.TP
.B \-s 題名, \-\-subject=題名
バグ報告の題名 (問題の簡潔な説明で、半角 60 文字以下) を設定する。
これを設定しないと、題名の確認を受けることになる。
.TP
.B \-S 重要度, \-\-severity=重要度
致命的 (critical), 重大 (grave), 深刻 (serious), 重要 (important),
通常 (normal), 軽度 (minor), 要望 (wishlist) の中から、重要度を指定
する。
.TP
.B \-\-smtphost=ホスト[:ポート]
ローカルの
.B /usr/sbin/sendmail
プログラムの代わりに、バグ報告送信用として
.B ホスト
にあるメール転送エージェント (MTA) を使う。一般には、ISP の送信メール
サーバとなるべきである。自分のマシン上で稼働しているメールサーバがある
なら、'localhost' を使うこともできる。
.B ポート
を指定しなければ、SMTP の標準ポートである 25 番ポートが使われる。
.TP
.B \-\-tls
SMTP の使用時に、メールサーバへ安全に接続するために Transport Layer
 Security (TLS) 暗号化を使う。いくつかの SMP サーバでは、本オプション
が必要となるだろう。
.TP
.B \-\-smtpuser=ユーザ名
SMTP の使用時に、認証用として指定した
.B ユーザ名
を使う。
.TP
.B \-\-smtppasswd=パスワード
SMTP の使用時に、認証用として指定した
.B パスワード
を使う。コマンドライン上や設定ファイル内でパスワードが指定されていなけ
れば、それを尋ねる確認が表示されるだろう。

マルチユーザシステムでの本オプションの使用は、危険である。代わりに本オ
プションを .reportbugrc 内で設定し、それをユーザだけが読めるようにして
おくべできである (chmod 600 $HOME/.reportbugrc と実行するなど)。
.TP
.B \-t 種類, \-\-type=種類
送信されるバグ報告の種類を指定する。現在のところ、gnats か debbugs の
いずれかを指定できる。
.TP
.B \-T タグ, \-\-tag=タグ
バグ報告に挿入されるタグを指定する。複数の \-T や \-\-tag 引数を使うこ
とにより、複数のタグを指定できる。

代わりに
.B none
という 'タグ' を指定して、タグを指定しなかった際のタグ確認を飛ばすこと
もできる。これはコマンドライン上で指定されたあらゆるタグも無視する。
.TP
.B \-\-template
バグ報告のテンプレートを標準出力に出力する。
.TP
.B \-v, \-\-verify
バグ報告前に、(インストール済であれば) debsums を使ってパッケージの
整合性を検証する。
.TP
.B \-V バージョン, \-\-package\-version=バージョン
問題が見つかったパッケージのバージョンを指定する。おそらくインストール
不可能なパッケージや、別のシステムにインストールされているパッケージの
バグ報告を行なう際に、もっとも役立つだろう。
.TP
.B \-x, \-\-no\-cc
報告者 (あなた自身) にバグ報告のブラインドカーボンコピー (Bcc) を送信
しない。
.TP
.B \-z, \-\-no\-compress
コメントや空行の削除による設定ファイルの圧縮を行なわない。
.SH 例
.TP
.B reportbug lynx-ssl
lynx-ssl パッケージのバグを報告する。
.TP
.B reportbug \-\-path \-\-file=ls
\fBls\fP というパス内のプログラムが含まれるインストール済パッケージの
バグを報告する。
.SH 設定ファイル
バージョン 0.22 以降、
.B reportbug
はシンプルな動作制御ファイル構文に対応している。コマンドは
.B /etc/reportbug.conf
および
.B $HOME/.reportbugrc
から読み込まれ、後者内のコマンドは前者のものを上書きする。コマンドに大
文字小文字の区別はなく、現在のところ 0 ないし 1 個の引数を持つ。空白を
含む引数はクォートで囲まなければならない。# で始まるあらゆる行はコメン
トとみなされ、無視される。

一般に、
.B reportbug
用のオプションで GNU のロングオプションに相当するものには、\-\- 文
字列で始まらなくても対応している。利用可能な全オプションについては、
デフォルトの
.B /etc/reportbug.conf
を参照。
.SH 環境変数
.TP
.B VISUAL
バグ報告の編集に使うエディタ。
.TP
.B EDITOR
バグ報告の編集に使うエディタ (VISUAL に上書きされる)。
.TP
.B EMAIL, REPORTBUGEMAIL, DEBEMAIL
報告者の from アドレスとして使われる電子メールアドレス。デフォルトでは、
報告者のユーザ名と /etc/mailname から取得される。
.TP
.B DEBFULLNAME, DEBNAME, NAME
使われる実名。デフォルトでは /etc/passwd から取得される。
.TP
.B REPLYTO
送信メール内の Reply-To ヘッダ用アドレス。
.TP
.B MAILCC
電子メール上で指定した CC アドレスを使う。同じ目的のために
.B -H
オプションも使えることに注意 (Bcc も同様)。
.TP
.B MAILBCC
報告者の電子メールアドレスの代わりに、指定した Bcc アドレスを使う (
.B bug
の wishlist 内の Herbert Thielen による提案を元にした Cc と Bcc)。
.TP
.B http_proxy
BTS 問い合せを処理するプロキシサーバのアドレスを指定する。必要なあらゆる
ポート番号を含む、完全な
.B HTTP
URL でなければならない (ホスト名だけを指定したり、80 番以外のポートを
指定しないと、まったく動作しないであろう)。
.SH 注意
コマンドライン引数の順序に関して、Python の getopt モジュールは
GNU getopt() よりも神経質である。すべてのスイッチはパッケージ名の
前に指定されなければならない。

おそらく
.B reportbug
は、
.B bugzilla
(GNOME および Mozilla プロジェクトで使われている) や
.B jitterbug
(Samba, AbiSource, FreeCiv で使われている) のような他のバグ追跡システム
との互換性を持つべきなのだろうが、そうはなっていない。
.SH 関連項目
querybts(1)
.SH 著者
Chris Lawrence <lawrencc@debian.org>.
.SH 翻訳者
田村 一平 <ippei1@bb.mbn.or.jp>
