#!/usr/bin/python2.3
# -*- python -*-

import os

OUT=os.fdopen(3, 'w')

envprint = False
for var in ['EDITOR', 'VISUAL', 'REPORTBUGEMAIL', 'DEBEMAIL', 'EMAIL',
            'DEBFULLNAME', 'DEBNAME', 'NAME']:
    if var in os.environ:
        if not envprint:
            print >> OUT, '** Environment settings:'
            envprint = True
        print >> OUT, '%s="%s"' % (var, os.environ[var])

USERFILE = os.path.expanduser('~/.reportbugrc')
if os.path.exists(USERFILE):
    if envprint:
        print >> OUT
    print >> OUT, '** %s:' % USERFILE
    for line in file(USERFILE):
        if line and line[0] != '#' and line.strip():
            OUT.write(line)
